### ISSUE TITLE
Add support for avatar from posting_json_metadata

### ISSUE THREAD

**Issue by tiotdev** [steemit/imagehoster#113]
The new account_update2 allows to broadcast posting_json_metadata with the posting key. This would allow to update the profile image without needing the active key, but steemitimages does currently not consider posting_json_metadata for the avatar.

For example: https://steemd.com/@tftest4 has a profile_image set in the posting_json_metadata, but the avatar is not reflected on https://steemitimages.com/u/tftest4/avatar/, requiring applications to fetch the profile image manually, resulting in many unnecessary API calls

**Comment by tiotdev** [comment]
On a quick look it seems like it would be enough to change `json_metadata` to `posting_json_metadata` in https://github.com/steemit/imagehoster/blob/8d1b4f5eb8d76be7df9f69ea4dd3e98bf4a6dfe4/src/avatar.ts

**Comment by tiotdev** [comment]
Any ETA on this? 
We allow our users to update their profile without the active key using account_update2, some are complaining that they cannot update their profile image.

**Comment by roadscape** [comment]
Initially, we need to support reading from both `json_metadata` and `posting_json_metadata`.

- The `/u/<username>/avatar/` endpoint should continue to deliver the image from `json_metadata` by default.
- We should add an optional query string param (`?beta=1`) which instructs the endpoint to serve the profile image from `posting_json_metadata`.
- Eventually, we will use `posting_json_metadata` for all requests and remove the flag.
