### ISSUE TITLE
Caching headers!

### ISSUE THREAD

**Issue by jnordberg** [steemit/imagehoster#32]
Not sure if this is the same app that runs on steemitimages.com but if it is, please for the love of god add some caching headers to the images

**Comment by GarethNelson** [comment]
Elaborating on this: it should work fine if we add 2 things:

1 - an ETag header which references a hash of the underlying image
2 - an Expires header which references the expiry time of the amazon S3 signed URL

Further, if we can keep images in S3 for longer, we can add a longer expiry to the S3 URLs and up the "Expires" header
